POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibXdlaXNlcjIiLCJpZCI6IjYyMTRhYmY2YTcxNzI5NjI0YjQ2OGEzMSIsImlhdCI6MTY0NTUyMjE0M30.tcGXd40vUZs96QlMclwr6ymBWv5nGgs_wN9M9RmQOwM

{
    "title": "Michael's Second Blog",
    "author": "Michael Weiser",
    "url": "michaelsblog.edu",
    "likes": 12
}